apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.name}}
spec:
  type: service
  lifecycle: production
  owner: {{cookiecutter.team}}
  system: {{cookiecutter.system}}
